install:
	npm ci

start:
	npm start

dev:
	cd frontend && npm run dev

build:
	cd frontend && npm run build

lint:
	npx eslint --ext js,jsx .

fix:
	npx eslint --fix .

localStart:
	npm run dev

vite:
	npx vite preview --port 3000

backend:
	npm start